using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CloudSim.Sharp
{
    internal enum DataCloudTags
    {
        BASE = 400,
        RM_BASE = 500,
        CTLG_BASE = 600,

        #region GENERAL TAGS
        DEFAULT_MTU = 1500,
        PKT_SIZE = DEFAULT_MTU * 100,
        DEFAULT_STORAGE_SIZE = 10000000,
        REGISTER_REPLICA_CTLG = BASE + 1,
        INQUIRY_LOCAL_RC_LIST = BASE + 2,
        INQUIRY_GLOBAL_RC_LIST = BASE + 3,
        INQUIRY_RC_LIST = BASE + 4,
        INQUIRY_RC_RESULT = BASE + 5,
        DATAcloudlet_SUBMIT = BASE + 6,
        #endregion

        #region REPLICA MANAGER TAGS
        FILE_REQUEST = RM_BASE + 1,
        FILE_DELIVERY = RM_BASE + 2,
        FILE_ADD_MASTER = RM_BASE + 10,
        FILE_ADD_MASTER_RESULT = RM_BASE + 11,
        FILE_ADD_REPLICA = RM_BASE + 12,
        FILE_ADD_REPLICA_RESULT = RM_BASE + 13,
        FILE_ADD_SUCCESSFUL = RM_BASE + 20,
        FILE_ADD_ERROR_STORAGE_FULL = RM_BASE + 21,
        FILE_ADD_ERROR_EMPTY = RM_BASE + 22,
        FILE_ADD_ERROR_EXIST_READ_ONLY = RM_BASE + 23,
        FILE_ADD_ERROR = RM_BASE + 24,
        FILE_ADD_ERROR_ACCESS_DENIED = RM_BASE + 25,
        FILE_DELETE_MASTER = RM_BASE + 30,
        FILE_DELETE_MASTER_RESULT = RM_BASE + 31,
        FILE_DELETE_REPLICA = RM_BASE + 32,
        FILE_DELETE_REPLICA_RESULT = RM_BASE + 33,
        FILE_DELETE_SUCCESSFUL = RM_BASE + 40,
        FILE_DELETE_ERROR = RM_BASE + 41,
        FILE_DELETE_ERROR_READ_ONLY = RM_BASE + 42,
        FILE_DELETE_ERROR_DOESNT_EXIST = RM_BASE + 43,
        FILE_DELETE_ERROR_IN_USE = RM_BASE + 44,
        FILE_DELETE_ERROR_ACCESS_DENIED = RM_BASE + 45,
        FILE_MODIFY = RM_BASE + 50,
        FILE_MODIFY_RESULT = RM_BASE + 51,
        FILE_MODIFY_SUCCESSFUL = RM_BASE + 60,
        FILE_MODIFY_ERROR = RM_BASE + 61,
        FILE_MODIFY_ERROR_READ_ONLY = RM_BASE + 62,
        FILE_MODIFY_ERROR_DOESNT_EXIST = RM_BASE + 63,
        FILE_MODIFY_ERROR_IN_USE = RM_BASE + 64,
        FILE_MODIFY_ERROR_ACCESS_DENIED = RM_BASE + 65,
        #endregion

        #region REPLICA CATALOGUE TAGS
        CTLG_GET_REPLICA = CTLG_BASE + 1,
        CTLG_REPLICA_DELIVERY = CTLG_BASE + 2,
        CTLG_GET_REPLICA_LIST = CTLG_BASE + 3,
        CTLG_REPLICA_LIST_DELIVERY = CTLG_BASE + 4,
        CTLG_GET_FILE_ATTR = CTLG_BASE + 5,
        CTLG_FILE_ATTR_DELIVERY = CTLG_BASE + 6,
        CTLG_FILTER = CTLG_BASE + 7,
        CTLG_FILTER_DELIVERY = CTLG_BASE + 8,
        CTLG_ADD_MASTER = CTLG_BASE + 10,
        CTLG_ADD_MASTER_RESULT = CTLG_BASE + 11,
        CTLG_ADD_MASTER_SUCCESSFUL = CTLG_BASE + 12,
        CTLG_ADD_MASTER_ERROR = CTLG_BASE + 13,
        CTLG_ADD_MASTER_ERROR_FULL = CTLG_BASE + 14,
        CTLG_DELETE_MASTER = CTLG_BASE + 20,
        CTLG_DELETE_MASTER_RESULT = CTLG_BASE + 21,
        CTLG_DELETE_MASTER_SUCCESSFUL = CTLG_BASE + 22,
        CTLG_DELETE_MASTER_ERROR = CTLG_BASE + 23,
        CTLG_DELETE_MASTER_DOESNT_EXIST = CTLG_BASE + 24,
        CTLG_DELETE_MASTER_REPLICAS_EXIST = CTLG_BASE + 25,
        CTLG_ADD_REPLICA = CTLG_BASE + 30,
        CTLG_ADD_REPLICA_RESULT = CTLG_BASE + 31,
        CTLG_ADD_REPLICA_SUCCESSFUL = CTLG_BASE + 32,
        CTLG_ADD_REPLICA_ERROR = CTLG_BASE + 33,
        CTLG_ADD_REPLICA_ERROR_DOESNT_EXIST = CTLG_BASE + 34,
        CTLG_ADD_REPLICA_ERROR_FULL = CTLG_BASE + 35,
        CTLG_DELETE_REPLICA = CTLG_BASE + 40,
        CTLG_DELETE_REPLICA_RESULT = CTLG_BASE + 41,
        CTLG_DELETE_REPLICA_SUCCESSFUL = CTLG_BASE + 42,
        CTLG_DELETE_REPLICA_ERROR = CTLG_BASE + 43,
        CTLG_DELETE_REPLICA_ERROR_DOESNT_EXIST = CTLG_BASE + 44,
        CTLG_MODIFY_MASTER_RESULT = CTLG_BASE + 51,
        CTLG_MODIFY_MASTER_SUCCESSFUL = CTLG_BASE + 52,
        CTLG_MODIFY_MASTER_ERROR = CTLG_BASE + 53,
        CTLG_MODIFY_MASTER_ERROR_DOESNT_EXIST = CTLG_BASE + 54,
        CTLG_MODIFY_MASTER_ERROR_READ_ONLY = CTLG_BASE + 55
        #endregion

    }
}
